
services:
  - type: web
    name: kojomoney
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BUILD_MODE
        value: server
